### PR TITLE
Fixes #5 - Implement OverviewCard component

### LINKED ISSUE #5: Created Card Component for the overview items
The overview Items are currently not separate components.
image

Extract the code as separate reusable component and update the OverviewPage
Acceptance Criterias:
- Component is using Props to pass the Values
- Component can use Slots to pass in the Icons

### PR DESCRIPTION
**Pull request by sabifa**
As @resparx comment was already 3 days old I though I could give it a shot 🙂

Title and count are provided via props, the image via a slot - I hope this solves the issues. If there is something missing, please let me know 😅

### CODE REVIEW

**Comment by sabifa** [comment]
@valentinvieriu It seems like the PR's don't count towards the Hacktoberfest score. Is there the possibility for you to change that? 😄 
image

**Comment by valentinvieriu** [comment]
Can, you check now? I've added the hacktoberfest label to the pull request too
@sabifa

Can you also sign our  Contributor License Agreement? Is needed for any code that is pushed to this repo

**Comment by sabifa** [comment]
Unfortunately it's still the same.. Maybe it needs some time to refresh?
I've already signed the CLA multiple times now, somehow it doesn't refresh 🤔 Can you rerun the checks maybe?
image

**Comment by valentinvieriu** [comment]
@sabifa Sorry, try now. It seems they changed the rule yesterday? I've added hacktoberfet to the topic of this repo.

**Comment by sabifa** [comment]
image
Works! Yea they've added some rules to prevent PR spam :)

**Comment by valentinvieriu** [comment]
@sabifa sorry for this, we had a pull request that was just merged, we have a new way to use icons, as components.
Can you adjust your pull request?

**Comment by sabifa** [comment]
I've extracted the icons into seperate components. 

I'm still struggling with the CLA, I already signed it like 10 times and it still shows that it's not signed yet. Any tips?

**Comment by sabifa** [comment]
Found the issue.. I forked the repo using my new git account but made the commits on my old account 😅 Sorry for the confusion!

I've force pushed the branch again with the correct account.

**Comment by valentinvieriu** [comment]
@sabifa I was expecting something like that to be honest, happened to me too in the past, was using 2 emails when pushing.
Glad it worked out, and your changes are merged!
If you liked the experience, feel free to contribute more to this small project.

**Pull request merged**
